### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by leeoniya** [tivac/es6-watching#1]
@tivac 

Thanks, this works like a charm and the fact that it installs all deps in a few secs in 342 files / 4.33 MB restores some of my faith in the entire zoo of tooling/env-setup required these days.

Wonder how a comparable Typescript setup would fare...I assume also pretty minimal?

**Comment by tivac** [comment]
Seems easy enough.

https://github.com/tivac/es6-watching/tree/typescript

**Comment by leeoniya** [comment]
👍
